### ISSUE TITLE
Incorrect License Change from MIT to ISC

### ISSUE THREAD

**Issue by xpzouying** [phuslu/shardmap#2]
I noticed that the original project was under the MIT license, but it seems you've changed it to the ISC license after forking. While the MIT and ISC licenses are similar, they are not the same, and changing the license without the explicit permission of the original authors might not be appropriate or legal.

**Comment by phuslu** [comment]
sorry for mistake. I saw the github detected the original license as "ISC", please see https://github.com/tidwall/shardmap/blob/master/LICENSE
![image](https://github.com/phuslu/shardmap/assets/195836/1e29efb0-2ef6-40f9-beef-5c16c4ac4b69)

So I think it might a typo and change it to ISC, now I changed it back
